package main

import (
	"bytes"
	"encoding/binary"
	"fmt"
	"math"
)

// GenerateSTLBytes creates STL binary data from GitHub contribution data.
// This is the WASM-compatible version that returns bytes instead of writing to a file.
func GenerateSTLBytes(contributions [][][]ContributionDay, username string, startYear, endYear int) ([]byte, error) {
	if len(contributions) == 0 {
		return nil, fmt.Errorf("contributions data cannot be empty")
	}

	width, depth := CalculateMultiYearDimensions(len(contributions))

	// Find global max contribution across all years
	maxContribution := findMaxContributionsAcrossYears(contributions)

	// Generate all triangles
	var allTriangles []Triangle

	// Generate base
	baseTriangles, err := CreateCuboidBase(width, depth)
	if err != nil {
		return nil, fmt.Errorf("failed to generate base: %w", err)
	}
	allTriangles = append(allTriangles, baseTriangles...)

	// Generate columns for each year (process in reverse order so most recent year is at the front)
	for i := len(contributions) - 1; i >= 0; i-- {
		yearOffset := len(contributions) - 1 - i
		triangles, err := CreateContributionGeometry(contributions[i], yearOffset, maxContribution)
		if err != nil {
			return nil, fmt.Errorf("failed to generate geometry for year %d: %w", i, err)
		}
		allTriangles = append(allTriangles, triangles...)
	}

	// Generate STL binary
	stlData, err := writeSTLToBytes(allTriangles)
	if err != nil {
		return nil, fmt.Errorf("failed to write STL: %w", err)
	}

	return stlData, nil
}

// writeSTLToBytes writes triangles to a byte buffer in binary STL format.
func writeSTLToBytes(triangles []Triangle) ([]byte, error) {
	buf := new(bytes.Buffer)

	// Write 80-byte header
	header := make([]byte, 80)
	copy(header, []byte("Generated by GitHub Skyline WASM"))
	if _, err := buf.Write(header); err != nil {
		return nil, err
	}

	// Write triangle count (uint32)
	triangleCount := uint32(len(triangles))
	if err := binary.Write(buf, binary.LittleEndian, triangleCount); err != nil {
		return nil, err
	}

	// Write each triangle
	for _, triangle := range triangles {
		if err := writeTriangle(buf, triangle.ToFloat32()); err != nil {
			return nil, err
		}
	}

	return buf.Bytes(), nil
}

// writeTriangle writes a single triangle in STL binary format.
func writeTriangle(buf *bytes.Buffer, t TriangleFloat32) error {
	// Write normal vector
	if err := writeFloat32(buf, t.Normal.X); err != nil {
		return err
	}
	if err := writeFloat32(buf, t.Normal.Y); err != nil {
		return err
	}
	if err := writeFloat32(buf, t.Normal.Z); err != nil {
		return err
	}

	// Write vertex 1
	if err := writeFloat32(buf, t.V1.X); err != nil {
		return err
	}
	if err := writeFloat32(buf, t.V1.Y); err != nil {
		return err
	}
	if err := writeFloat32(buf, t.V1.Z); err != nil {
		return err
	}

	// Write vertex 2
	if err := writeFloat32(buf, t.V2.X); err != nil {
		return err
	}
	if err := writeFloat32(buf, t.V2.Y); err != nil {
		return err
	}
	if err := writeFloat32(buf, t.V2.Z); err != nil {
		return err
	}

	// Write vertex 3
	if err := writeFloat32(buf, t.V3.X); err != nil {
		return err
	}
	if err := writeFloat32(buf, t.V3.Y); err != nil {
		return err
	}
	if err := writeFloat32(buf, t.V3.Z); err != nil {
		return err
	}

	// Write attribute byte count (uint16) - always 0
	if err := binary.Write(buf, binary.LittleEndian, uint16(0)); err != nil {
		return err
	}

	return nil
}

// writeFloat32 writes a float32 value in little-endian format.
func writeFloat32(buf *bytes.Buffer, value float32) error {
	return binary.Write(buf, binary.LittleEndian, math.Float32bits(value))
}
